/*
 * WCAG 2.2 relative-luminance contrast — pure TS, zero deps.
 * One source for both the showcase badges and the committed contrast matrix
 * (ADR-0002 §8). Foreground/background pairs the design uses are enumerated in
 * DOCUMENTED_PAIRS; extend as new surfaces ship.
 */

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

const HEX_RE = /^#?([0-9a-f]{6}|[0-9a-f]{3})$/i;

export function parseHex(hex: string): Rgb {
  const m = hex.trim().match(HEX_RE);
  if (!m) {
    throw new Error(`Invalid hex color: "${hex}" — expected #rgb or #rrggbb.`);
  }
  const v = m[1];
  const full = v.length === 3 ? v.split('').map((c) => c + c).join('') : v;
  return {
    r: parseInt(full.slice(0, 2), 16),
    g: parseInt(full.slice(2, 4), 16),
    b: parseInt(full.slice(4, 6), 16),
  };
}

function channelLuminance(c: number): number {
  const s = c / 255;
  return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
}

export function relativeLuminance({ r, g, b }: Rgb): number {
  return 0.2126 * channelLuminance(r) + 0.7152 * channelLuminance(g) + 0.0722 * channelLuminance(b);
}

export function contrastRatio(fgHex: string, bgHex: string): number {
  const l1 = relativeLuminance(parseHex(fgHex));
  const l2 = relativeLuminance(parseHex(bgHex));
  const [lighter, darker] = l1 >= l2 ? [l1, l2] : [l2, l1];
  return (lighter + 0.05) / (darker + 0.05);
}

export interface PairEvaluation {
  ratio: number;
  passesAA: boolean;
  passesAAA: boolean;
}

export function evaluatePair(fgHex: string, bgHex: string): PairEvaluation {
  const ratio = contrastRatio(fgHex, bgHex);
  return {
    ratio,
    passesAA: ratio >= 4.5,
    passesAAA: ratio >= 7,
  };
}

export interface TokenPair {
  fgName: string;
  bgName: string;
  fgHex: string;
  bgHex: string;
  note?: string;
}

/*
 * Canonical token hex values — kept in sync with the @theme block in
 * src/styles/global.css. Brand tokens are sourced from Figma node 29:5768;
 * status tokens (--color-pass / --color-fail) are utility colors local to
 * this codebase. If any value changes in global.css, update it here too —
 * the matrix is regenerated by `pnpm contrast-matrix` from this table.
 */
export const TOKEN_HEX: Record<string, string> = {
  '--color-accent': '#FFB900',
  '--color-accent-deep': '#E8920C',
  '--color-gradient-to': '#FF7A4D',
  '--color-bg': '#FDF9F2',
  '--color-bg-alt': '#FBF7EE',
  '--color-surface': '#FFFFFF',
  '--color-border': '#ECE4D5',
  '--color-ink-heading': '#121820',
  '--color-ink-body': '#1A1A1A',
  '--color-ink-muted': '#7A7468',
  '--color-pass': '#15803D',
  '--color-fail': '#B91C1C',
};

function pair(fgName: string, bgName: string, note?: string): TokenPair {
  return {
    fgName,
    bgName,
    fgHex: TOKEN_HEX[fgName],
    bgHex: TOKEN_HEX[bgName],
    ...(note ? { note } : {}),
  };
}

export const DOCUMENTED_PAIRS: TokenPair[] = [
  pair('--color-ink-heading', '--color-bg'),
  pair('--color-ink-body', '--color-bg'),
  pair('--color-ink-muted', '--color-bg'),
  pair('--color-ink-body', '--color-surface'),
  pair('--color-ink-muted', '--color-surface', 'Caption text inside cards'),
  pair('--color-ink-body', '--color-bg-alt'),
  pair('--color-ink-heading', '--color-surface'),
  pair('--color-surface', '--color-ink-heading', 'Light text on dark surface (glow card)'),
  pair('--color-ink-body', '--color-accent', 'CTA button text on amber-gold'),
  pair('--color-ink-heading', '--color-accent', 'Alternate CTA text'),
  pair('--color-surface', '--color-pass', 'PASS badge text'),
  pair('--color-surface', '--color-fail', 'FAIL badge text'),
];
