/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OOrgSlugRouteImport } from './routes/o/$orgSlug'
import { Route as OOrgSlugIndexRouteImport } from './routes/o/$orgSlug/index'
import { Route as OOrgSlugAgentsIndexRouteImport } from './routes/o/$orgSlug/agents/index'
import { Route as OOrgSlugAgentsAgentIdRouteImport } from './routes/o/$orgSlug/agents/$agentId'
import { Route as OOrgSlugAgentsAgentIdIndexRouteImport } from './routes/o/$orgSlug/agents/$agentId/index'
import { Route as OOrgSlugAgentsAgentIdVersionsRouteImport } from './routes/o/$orgSlug/agents/$agentId/versions'
import { Route as OOrgSlugAgentsAgentIdToolsRouteImport } from './routes/o/$orgSlug/agents/$agentId/tools'
import { Route as OOrgSlugAgentsAgentIdSkillsRouteImport } from './routes/o/$orgSlug/agents/$agentId/skills'
import { Route as OOrgSlugAgentsAgentIdKnowledgeBasesRouteImport } from './routes/o/$orgSlug/agents/$agentId/knowledge-bases'
import { Route as OOrgSlugAgentsAgentIdKnowledgeBasesIndexRouteImport } from './routes/o/$orgSlug/agents/$agentId/knowledge-bases/index'
import { Route as OOrgSlugAgentsAgentIdKnowledgeBasesWebRouteImport } from './routes/o/$orgSlug/agents/$agentId/knowledge-bases/web'
import { Route as OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRouteImport } from './routes/o/$orgSlug/agents/$agentId/knowledge-bases/documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugRoute = OOrgSlugRouteImport.update({
  id: '/o/$orgSlug',
  path: '/o/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OOrgSlugRoute,
} as any)
const OOrgSlugAgentsIndexRoute = OOrgSlugAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => OOrgSlugRoute,
} as any)
const OOrgSlugAgentsAgentIdRoute = OOrgSlugAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => OOrgSlugRoute,
} as any)
const OOrgSlugAgentsAgentIdIndexRoute =
  OOrgSlugAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgSlugAgentsAgentIdRoute,
  } as any)
const OOrgSlugAgentsAgentIdVersionsRoute =
  OOrgSlugAgentsAgentIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => OOrgSlugAgentsAgentIdRoute,
  } as any)
const OOrgSlugAgentsAgentIdToolsRoute =
  OOrgSlugAgentsAgentIdToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => OOrgSlugAgentsAgentIdRoute,
  } as any)
const OOrgSlugAgentsAgentIdSkillsRoute =
  OOrgSlugAgentsAgentIdSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => OOrgSlugAgentsAgentIdRoute,
  } as any)
const OOrgSlugAgentsAgentIdKnowledgeBasesRoute =
  OOrgSlugAgentsAgentIdKnowledgeBasesRouteImport.update({
    id: '/knowledge-bases',
    path: '/knowledge-bases',
    getParentRoute: () => OOrgSlugAgentsAgentIdRoute,
  } as any)
const OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute =
  OOrgSlugAgentsAgentIdKnowledgeBasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OOrgSlugAgentsAgentIdKnowledgeBasesRoute,
  } as any)
const OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute =
  OOrgSlugAgentsAgentIdKnowledgeBasesWebRouteImport.update({
    id: '/web',
    path: '/web',
    getParentRoute: () => OOrgSlugAgentsAgentIdKnowledgeBasesRoute,
  } as any)
const OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute =
  OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => OOrgSlugAgentsAgentIdKnowledgeBasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugRouteWithChildren
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/agents/$agentId': typeof OOrgSlugAgentsAgentIdRouteWithChildren
  '/o/$orgSlug/agents/': typeof OOrgSlugAgentsIndexRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases': typeof OOrgSlugAgentsAgentIdKnowledgeBasesRouteWithChildren
  '/o/$orgSlug/agents/$agentId/skills': typeof OOrgSlugAgentsAgentIdSkillsRoute
  '/o/$orgSlug/agents/$agentId/tools': typeof OOrgSlugAgentsAgentIdToolsRoute
  '/o/$orgSlug/agents/$agentId/versions': typeof OOrgSlugAgentsAgentIdVersionsRoute
  '/o/$orgSlug/agents/$agentId/': typeof OOrgSlugAgentsAgentIdIndexRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/documents': typeof OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/web': typeof OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/': typeof OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/agents': typeof OOrgSlugAgentsIndexRoute
  '/o/$orgSlug/agents/$agentId/skills': typeof OOrgSlugAgentsAgentIdSkillsRoute
  '/o/$orgSlug/agents/$agentId/tools': typeof OOrgSlugAgentsAgentIdToolsRoute
  '/o/$orgSlug/agents/$agentId/versions': typeof OOrgSlugAgentsAgentIdVersionsRoute
  '/o/$orgSlug/agents/$agentId': typeof OOrgSlugAgentsAgentIdIndexRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/documents': typeof OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/web': typeof OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases': typeof OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/o/$orgSlug': typeof OOrgSlugRouteWithChildren
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/agents/$agentId': typeof OOrgSlugAgentsAgentIdRouteWithChildren
  '/o/$orgSlug/agents/': typeof OOrgSlugAgentsIndexRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases': typeof OOrgSlugAgentsAgentIdKnowledgeBasesRouteWithChildren
  '/o/$orgSlug/agents/$agentId/skills': typeof OOrgSlugAgentsAgentIdSkillsRoute
  '/o/$orgSlug/agents/$agentId/tools': typeof OOrgSlugAgentsAgentIdToolsRoute
  '/o/$orgSlug/agents/$agentId/versions': typeof OOrgSlugAgentsAgentIdVersionsRoute
  '/o/$orgSlug/agents/$agentId/': typeof OOrgSlugAgentsAgentIdIndexRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/documents': typeof OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/web': typeof OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute
  '/o/$orgSlug/agents/$agentId/knowledge-bases/': typeof OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/agents/$agentId'
    | '/o/$orgSlug/agents/'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases'
    | '/o/$orgSlug/agents/$agentId/skills'
    | '/o/$orgSlug/agents/$agentId/tools'
    | '/o/$orgSlug/agents/$agentId/versions'
    | '/o/$orgSlug/agents/$agentId/'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/documents'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/web'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/agents'
    | '/o/$orgSlug/agents/$agentId/skills'
    | '/o/$orgSlug/agents/$agentId/tools'
    | '/o/$orgSlug/agents/$agentId/versions'
    | '/o/$orgSlug/agents/$agentId'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/documents'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/web'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases'
  id:
    | '__root__'
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/agents/$agentId'
    | '/o/$orgSlug/agents/'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases'
    | '/o/$orgSlug/agents/$agentId/skills'
    | '/o/$orgSlug/agents/$agentId/tools'
    | '/o/$orgSlug/agents/$agentId/versions'
    | '/o/$orgSlug/agents/$agentId/'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/documents'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/web'
    | '/o/$orgSlug/agents/$agentId/knowledge-bases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OOrgSlugRoute: typeof OOrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug': {
      id: '/o/$orgSlug'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug'
      preLoaderRoute: typeof OOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof OOrgSlugRoute
    }
    '/o/$orgSlug/agents/': {
      id: '/o/$orgSlug/agents/'
      path: '/agents'
      fullPath: '/o/$orgSlug/agents/'
      preLoaderRoute: typeof OOrgSlugAgentsIndexRouteImport
      parentRoute: typeof OOrgSlugRoute
    }
    '/o/$orgSlug/agents/$agentId': {
      id: '/o/$orgSlug/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/o/$orgSlug/agents/$agentId'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdRouteImport
      parentRoute: typeof OOrgSlugRoute
    }
    '/o/$orgSlug/agents/$agentId/': {
      id: '/o/$orgSlug/agents/$agentId/'
      path: '/'
      fullPath: '/o/$orgSlug/agents/$agentId/'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdIndexRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdRoute
    }
    '/o/$orgSlug/agents/$agentId/versions': {
      id: '/o/$orgSlug/agents/$agentId/versions'
      path: '/versions'
      fullPath: '/o/$orgSlug/agents/$agentId/versions'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdVersionsRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdRoute
    }
    '/o/$orgSlug/agents/$agentId/tools': {
      id: '/o/$orgSlug/agents/$agentId/tools'
      path: '/tools'
      fullPath: '/o/$orgSlug/agents/$agentId/tools'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdToolsRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdRoute
    }
    '/o/$orgSlug/agents/$agentId/skills': {
      id: '/o/$orgSlug/agents/$agentId/skills'
      path: '/skills'
      fullPath: '/o/$orgSlug/agents/$agentId/skills'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdSkillsRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdRoute
    }
    '/o/$orgSlug/agents/$agentId/knowledge-bases': {
      id: '/o/$orgSlug/agents/$agentId/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/o/$orgSlug/agents/$agentId/knowledge-bases'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdRoute
    }
    '/o/$orgSlug/agents/$agentId/knowledge-bases/': {
      id: '/o/$orgSlug/agents/$agentId/knowledge-bases/'
      path: '/'
      fullPath: '/o/$orgSlug/agents/$agentId/knowledge-bases/'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesIndexRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesRoute
    }
    '/o/$orgSlug/agents/$agentId/knowledge-bases/web': {
      id: '/o/$orgSlug/agents/$agentId/knowledge-bases/web'
      path: '/web'
      fullPath: '/o/$orgSlug/agents/$agentId/knowledge-bases/web'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesWebRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesRoute
    }
    '/o/$orgSlug/agents/$agentId/knowledge-bases/documents': {
      id: '/o/$orgSlug/agents/$agentId/knowledge-bases/documents'
      path: '/documents'
      fullPath: '/o/$orgSlug/agents/$agentId/knowledge-bases/documents'
      preLoaderRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRouteImport
      parentRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesRoute
    }
  }
}

interface OOrgSlugAgentsAgentIdKnowledgeBasesRouteChildren {
  OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute
  OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute
  OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute
}

const OOrgSlugAgentsAgentIdKnowledgeBasesRouteChildren: OOrgSlugAgentsAgentIdKnowledgeBasesRouteChildren =
  {
    OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute:
      OOrgSlugAgentsAgentIdKnowledgeBasesDocumentsRoute,
    OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute:
      OOrgSlugAgentsAgentIdKnowledgeBasesWebRoute,
    OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute:
      OOrgSlugAgentsAgentIdKnowledgeBasesIndexRoute,
  }

const OOrgSlugAgentsAgentIdKnowledgeBasesRouteWithChildren =
  OOrgSlugAgentsAgentIdKnowledgeBasesRoute._addFileChildren(
    OOrgSlugAgentsAgentIdKnowledgeBasesRouteChildren,
  )

interface OOrgSlugAgentsAgentIdRouteChildren {
  OOrgSlugAgentsAgentIdKnowledgeBasesRoute: typeof OOrgSlugAgentsAgentIdKnowledgeBasesRouteWithChildren
  OOrgSlugAgentsAgentIdSkillsRoute: typeof OOrgSlugAgentsAgentIdSkillsRoute
  OOrgSlugAgentsAgentIdToolsRoute: typeof OOrgSlugAgentsAgentIdToolsRoute
  OOrgSlugAgentsAgentIdVersionsRoute: typeof OOrgSlugAgentsAgentIdVersionsRoute
  OOrgSlugAgentsAgentIdIndexRoute: typeof OOrgSlugAgentsAgentIdIndexRoute
}

const OOrgSlugAgentsAgentIdRouteChildren: OOrgSlugAgentsAgentIdRouteChildren = {
  OOrgSlugAgentsAgentIdKnowledgeBasesRoute:
    OOrgSlugAgentsAgentIdKnowledgeBasesRouteWithChildren,
  OOrgSlugAgentsAgentIdSkillsRoute: OOrgSlugAgentsAgentIdSkillsRoute,
  OOrgSlugAgentsAgentIdToolsRoute: OOrgSlugAgentsAgentIdToolsRoute,
  OOrgSlugAgentsAgentIdVersionsRoute: OOrgSlugAgentsAgentIdVersionsRoute,
  OOrgSlugAgentsAgentIdIndexRoute: OOrgSlugAgentsAgentIdIndexRoute,
}

const OOrgSlugAgentsAgentIdRouteWithChildren =
  OOrgSlugAgentsAgentIdRoute._addFileChildren(
    OOrgSlugAgentsAgentIdRouteChildren,
  )

interface OOrgSlugRouteChildren {
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
  OOrgSlugAgentsAgentIdRoute: typeof OOrgSlugAgentsAgentIdRouteWithChildren
  OOrgSlugAgentsIndexRoute: typeof OOrgSlugAgentsIndexRoute
}

const OOrgSlugRouteChildren: OOrgSlugRouteChildren = {
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
  OOrgSlugAgentsAgentIdRoute: OOrgSlugAgentsAgentIdRouteWithChildren,
  OOrgSlugAgentsIndexRoute: OOrgSlugAgentsIndexRoute,
}

const OOrgSlugRouteWithChildren = OOrgSlugRoute._addFileChildren(
  OOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OOrgSlugRoute: OOrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
